version: ~> 1.0
os: linux
dist: focal
language: cpp

branches:
  only:
  - master

git:
  depth: 1
  quiet: true
  submodules: true

cache:
  apt: true
  ccache: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-11

arch:
  - arm64
  - s390x
  - ppc64le

env:
  global:
    - CXX=g++-11
    - CC=gcc-11
  jobs:
    - BUILD=unit
    - BUILD=snippet
    - BUILD=performance
    - BUILD=header

jobs:
  allow_failures:
    - os: linux
  fast_finish: true

install:
  - ccache --version
  - $CXX -v
  - cmake --version

before_script:
  - mkdir ../seqan3-build
  - cd ../seqan3-build
  - cmake ../seqan3/test/${BUILD} -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Wno-psabi" -DSEQAN3_VERBOSE_TESTS=OFF -DSEQAN3_BENCHMARK_MIN_TIME=0.01
  - |
    if [[ "${BUILD}" =~ ^(unit|header|snippet)$ ]]; then
      make gtest_build
    fi
  - |
    if [[ "${BUILD}" =~ ^(performance|header)$ ]]; then
      make gbenchmark_build
    fi

script:
  - export SEQAN3_NO_VERSION_CHECK=1
  - export CCACHE_COMPRESS=true
  - export CCACHE_COMPRESSLEVEL=6
  - export CCACHE_MAXSIZE=500M
  - make -k -j2
  - |
    if [[ "${BUILD}" =~ ^(snippet)$ ]]; then
      ctest . --output-on-failure
    else
      ctest . -j2 --output-on-failure
    fi

after_script:
  - ccache -s
